### ISSUE TITLE
mud io examples 08 sky flicker bug

### ISSUE THREAD

**Issue by kungfooman** [hugoam/mud#1]
Hi, really nice library you got here. You happen to know what causes this flicker bug? Its in Chrome and Firefox, but they use the same engine nonetheless internally:

https://youtu.be/S3soeMoBoa4

https://hugoam.github.io/mud-io/examples/08_sky.html

**Comment by hugoam** [comment]
I believe that this is just one of the object rotating slightly in front of the camera, causing a flickering (the camera positioning is not very clever right there).
you can try rotating the viewpoint with the mouse middle click to verify if it's indeed what's happening here or if it's really a rendering bug.

**Comment by kungfooman** [comment]
Thanks, yea, that "fixed" it :D
