### ISSUE TITLE
Example 06_particles does not render particles

### ISSUE THREAD

**Issue by hoelzl** [hugoam/mud#13]
When building and running example `06_particles` I would expect to see something similar to [the WebGL demo](https://hugoam.github.io/mud-io/examples/06_particles.html).

Instead I get this:

![image](https://user-images.githubusercontent.com/35998/50918030-687c9100-143f-11e9-81f0-4de62f9c8e04.png)

I can zoom and rotate, but no particles appear on the screen...

(Built from the latest master (00fc8af) using VS2017 on Windows 10 Pro 64 bit with GeForce GTX 1080 graphics card, driver version 417.35, 4k monitor.)

**Comment by hugoam** [comment]
This is probably due to the data files being out of sync. I updated them in https://github.com/hugoam/mud/commit/f38fdcfc88ff00e51352977de1dd8e0f47d70085, let me know if that fixes it.

**Comment by hoelzl** [comment]
Yes, this now works in both the OpenGL and the D3D configurations. Thanks a lot for the quick fixes.
