### ISSUE TITLE
Example 07_gltf renders materials incorrectly

### ISSUE THREAD

**Issue by hoelzl** [hugoam/mud#14]
When running example `07_gltf` the materials appear very different from the ones in [the WebGL version](https://hugoam.github.io/mud-io/examples/07_gltf.html):

<img width="801" alt="07_gltf_d_2019-01-09_18-58-33" src="https://user-images.githubusercontent.com/35998/50918509-b219ab80-1440-11e9-89f1-da3769f4b26b.png">
<img width="801" alt="07_gltf_d_2019-01-09_18-58-54" src="https://user-images.githubusercontent.com/35998/50918513-b5ad3280-1440-11e9-8ca5-9688f4bc2e81.png">
<img width="801" alt="07_gltf_d_2019-01-09_18-59-12" src="https://user-images.githubusercontent.com/35998/50918519-b9d95000-1440-11e9-87a5-606caca0039d.png">

(Built from the latest master (00fc8af) using VS2017 on Windows 10 Pro 64 bit with GeForce GTX 1080 graphics card, driver version 417.35, 4k monitor.)

**Comment by hugoam** [comment]
Strangely, this might be related to https://github.com/hugoam/mud/issues/11.
In this one you don't get a crash, but it seems what's missing is the generation of the prefiltered environment map (which is precisely the one that is crashing in https://github.com/hugoam/mud/issues/11).
Maybe try running in D3D mode like I advised in the other issue so we can know more about this issue.

**Comment by hoelzl** [comment]
It seems you're right. When running in D3D mode the image looks perfect.

**Comment by hugoam** [comment]
Could you give me the logs for this one too ? I want to be sure that the cause is indeed related to the other issue.

**Comment by hoelzl** [comment]
It seems that this issue was solved by f38fdcfc88ff00e51352977de1dd8e0f47d70085 for OpenGL as well. Just in case they are still of interest to you I've attached logs for the latest version with the glitch (74a83bfd02b80b3865d0b95a2e34ac4e0863579f `_old`) and a post-fix build (`_new`).

[07_gltf_console_output_old.txt](https://github.com/hugoam/mud/files/2746712/07_gltf_console_output_old.txt)
[07_gltf_debug_output_old.txt](https://github.com/hugoam/mud/files/2746713/07_gltf_debug_output_old.txt)

[07_gltf_console_output_new.txt](https://github.com/hugoam/mud/files/2746708/07_gltf_console_output_new.txt)
[07_gltf_debug_output_new.txt](https://github.com/hugoam/mud/files/2746710/07_gltf_debug_output_new.txt)

**Comment by hugoam** [comment]
Oh, right, I just saw that I updated the shaders also in that commit, so if they were out-of-date that could explain all sorts of visual issues.
