### ISSUE TITLE
Windows Subsystem for Linux compatibility?

### ISSUE THREAD

**Issue by CarvellScott** [hugoam/mud#3]
Hi, I was wondering if WSL compatibility would be a thing that mud may support. So far, on a mostly clean-ish installation, I run into several errors:

```
In file included from ../../../mud/3rdparty/glfw/src/internal.h:188:0,
                 from ../../../mud/3rdparty/glfw/src/context.c:28:
../../../mud/3rdparty/glfw/src/x11_platform.h:33:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
make[1]: *** [../../linux64_gcc/obj/x64/Debug/glfw/mud/3rdparty/glfw/src/context.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../../../mud/3rdparty/glfw/src/internal.h:188:0,
                 from ../../../mud/3rdparty/glfw/src/egl_context.c:28:
../../../mud/3rdparty/glfw/src/x11_platform.h:33:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
In file included from ../../../mud/3rdparty/glfw/src/internal.h:188:0,
                 from ../../../mud/3rdparty/glfw/src/glx_context.c:28:
../../../mud/3rdparty/glfw/src/x11_platform.h:33:22: fatal error: X11/Xlib.h: No such file or directory
compilation terminated.
make[1]: *** [../../linux64_gcc/obj/x64/Debug/glfw/mud/3rdparty/glfw/src/egl_context.o] Error 1
make[1]: *** [../../linux64_gcc/obj/x64/Debug/glfw/mud/3rdparty/glfw/src/glx_context.o] Error 1
make: *** [glfw] Error 2
make: *** Waiting for unfinished jobs....
make[1]: yacc: Command not found
make[1]: *** [../../../mud/3rdparty/bgfx/3rdparty/glsl-optimizer/src/glsl/glcpp/glcpp-parse.c] Error 127
make[1]: *** Waiting for unfinished jobs....
make: *** [glsl-optimizer] Error 2
In file included from ../../../mud/3rdparty/bgfx/src/glcontext_egl.cpp:9:0:
../../../mud/3rdparty/bgfx/src/renderer_gl.h:43:22: fatal error: GL/gl.h: No such file or directory
compilation terminated.
make[1]: *** [../../linux64_gcc/obj/x64/Debug/bgfx/mud/3rdparty/bgfx/src/glcontext_egl.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../../../mud/3rdparty/bgfx/src/glcontext_glx.cpp:9:0:
../../../mud/3rdparty/bgfx/src/renderer_gl.h:43:22: fatal error: GL/gl.h: No such file or directory
compilation terminated.
make[1]: *** [../../linux64_gcc/obj/x64/Debug/bgfx/mud/3rdparty/bgfx/src/glcontext_glx.o] Error 1
make: *** [bgfx] Error 2
```

**Comment by hugoam** [comment]
Hi ! WSL is actually the way I build it with gcc and clang, however I don't check it regularly (I rely on Travis CI for that).
Especially I didn't check it since I added glfw as a built dependencies (before we were just linking the one we found on the system), so it looks like this is the part that is broken (the building glfw part).
I'll look into it and let you know when I find the proper fix (looks like it's just missing a dependency on X11).

**Comment by hugoam** [comment]
Hey ! I tried again building it today and it works. I suppose then the problem is that you don't have some of the dependencies installed on WSL. If I remember correctly you need at least `build-essential` and `libX11-dev`.
```
sudo apt-get install build-essential libx11-dev
```
Let me know if that might be the issue.

**Comment by CarvellScott** [comment]
Hello again. I installed those dependencies, did a clean checkout, and before I could build again, I got another error, this time looking like something went weird with git:
```
Cloning into '3rdparty/GENie'...
remote: Counting objects: 6213, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 6213 (delta 33), reused 30 (delta 16), pack-reused 6162
Receiving objects: 100% (6213/6213), 3.51 MiB | 2.16 MiB/s, done.
Resolving deltas: 100% (4261/4261), done.
Checking connectivity... done.
fatal: reference is not a tree: 82cf20e4fb0472b69aac01afe3e79c7a207d631a
```
It's even weirder because I can navigate to GENie at that revision, but git can't.

**Comment by hugoam** [comment]
Hmmm... That's problematic. Git submodules are tricky beasts. In these kind of situations I would just delete the repository folder and `git clone --recursive` from scratch again. Can you tell me if that works ?

**Comment by CarvellScott** [comment]
Tried that, spent another part of the day trying to see if I could resolve whatever c++ errors were getting thrown at me by installing various libraries.

`sudo apt install xorg-dev` to try to get more X11 development (was trying to resolve something to do with XCursor, can't recall exactly what.
`sudo apt install bison flex` to deal with some error where /user/bin/yacc was not found.
`sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev` to try to address openGL stuff missing.

**Comment by hugoam** [comment]
Could you send me a log of the build errors you're getting at this point ?

**Comment by CarvellScott** [comment]
I tried reinstalling Ubuntu via WSL to see if that fixed the issue. After doing a few installs of packages to catch up to where I left off, still no success:

`~/Muhznit/gitrepos/mud-sample/build/projects/gmake-linux$ make config=debug64 -j8
==== Building vg (debug64) ====
==== Building json11 (debug64) ====
==== Building lua (debug64) ====
==== Building stb_rect_pack (debug64) ====
==== Building fcpp (debug64) ====
==== Building glslang (debug64) ====
==== Building glsl-optimizer (debug64) ====
==== Building spirv-opt (debug64) ====
==== Building bx (debug64) ====
==== Building bimg (debug64) ====
==== Building bimg_decode (debug64) ====
==== Building glfw (debug64) ====
==== Building stb_image (debug64) ====
==== Building mud (debug64) ====
==== Building bgfx (debug64) ====
==== Building shaderc (debug64) ====
==== Building mud_gfx (debug64) ====
==== Building 00_cube (debug64) ====
==== Building 00_tutorial (debug64) ====
==== Building 01_shapes (debug64) ====
==== Building 02_camera (debug64) ====
==== Building 04_lights (debug64) ====
==== Building 06_particles (debug64) ====
==== Building 03_materials (debug64) ====
==== Building 04_sponza (debug64) ====
Linking 00_cube
Linking 01_shapes
Linking 03_materials
Linking 04_lights
Linking 06_particles
Linking 02_camera
Linking 00_tutorial
Linking 04_sponza
../../linux64_gcc/bin/liblua_d.a(loslib.o): In function `os_tmpname':
/home/muhznit/Muhznit/gitrepos/mud-sample/build/projects/gmake-linux/../../../mud/3rdparty/.lua.//loslib.c.:.169/:linux64_gcc /warningbin:/ liblua_d.athe( loslib.ouse) :of  In` tmpnamfunction'  `isos_tmpname 'dangerous:,
 /betterhome /usemuhznit /`.Muhznitmkstemp./'/gitrepos
./..mud./-/linux64_gccsample.//.binbuild///linux64_gccliblua_d.aprojects/(/binloslib.ogmake/)-libglsl:linux- /optimizer_d.aIn.( .pp.ofunction/.) ..:`./ os_tmpname/.In'.. :./function
/linux64_gcc /mud/`home/binglcpp_preprocess/3rdparty/.'muhznit/liblua_d.a.:/lua(/
Muhznit/loslib.o.//loslib.c).homegitrepos::///169 linux64_gccmuhznitmud:In//-  bin.Muhznitsamplewarningfunction/.//: liblua_d.a/gitreposbuild `(.//theos_tmpnameloslib.o.mudprojects ')/-/use::linux64_gccsamplegmake
 //-of/Inbinbuildlinux. home. ///.`/.functionliblua_d.aprojects./tmpnammuhznit/ (/..'/.`loslib.ogmake/. Muhznit.os_tmpname)-./is//':linux.linux64_gcc gitreposlinux64_gcc: ///dangerous//
In..bin,mudbin/ ../ -/homefunction//liblua_d.abettersampleliblua_d.a/ .mud( /(muhznit`./loslib.ousebuildloslib.o/os_tmpname/3rdparty) /)Muhznit'./:`projects:/:.lua mkstemp/ gitrepos
//In'gmakeIn//mudloslib.c
- mudhome/:function.linuxfunction-/3rdparty169 ./ samplemuhznit/:`/.`//bgfx os_tmpname..os_tmpnamebuildMuhznit/warning'./'//3rdparty::/.:projectsgitrepos/
linux64_gcc.
//glslthe////gmakemud- homebin.home--optimizeruse//./linuxsample/ muhznitlibglsl/muhznit//srcof/-mud/.build/ Muhznitoptimizer_d.a/Muhznit./glsl`/(3rdparty//projects/tmpnamgitrepospp.o/gitrepos./glcpp'/)lua/.gmake/ mud:/mud/-pp.cis- loslib.c-.linux: sampleIn:sample./225dangerous/ 169//.:,buildfunction:buildmud.  /  ///undefinedbetterprojects`warningprojects3rdparty.  /glcpp_preprocess://.referenceusegmake' gmakelua/  -:the-/.to`linux
 linuxloslib.c. mkstemp//use/:/`'.home .169mudglcpp_lex_set_source_string
./of.:/'./muhznit / 3rdparty
../`.warning///.Muhznittmpnam.:luahome.//'/ //..gitrepos .theloslib.cmuhznit/./is. :/linux64_gcc/mud /use169Muhznit/mud-dangerousmud :/bin/sample,/of gitrepos/3rdparty/ 3rdparty warning/libglsl/buildbetter/`:mud-lua/ luatmpnam -optimizer_d.a/projectsuse/'thesample(loslib.c/ loslib.c  /pp.o:gmake`:isusebuild)169-mkstemp169  /::linux':dangerousofprojects  /
 , /Inwarning..warning `gmake :..:bettertmpnam-function //  'linux the..theuse /` ..  is.glcpp_preprocessuse//use` .' .linux64_gcc mkstempdangerous/:of./of',.
 /bin
 ./`mud/`.better/hometmpnam/libglsltmpnam. ./'3rdparty-'/use.muhznit /optimizer_d.a . //isbgfx(is.`mudMuhznit /pp.o /mkstemp//dangerous3rdparty)dangerouslinux64_gcc'3rdpartygitrepos,/:,/
// glsl  bin.bgfxmudbetter-Inbetter/./- optimizer  libglsl/3rdpartysampleuse/functionuse-.// src  optimizer_d.a.glslbuild`/``(/-/mkstempglslglcpp_preprocessmkstemppp.olinux64_gccoptimizerprojects'/'')///
glcpp:
:binsrcgmake./
. //-.pp.c/.Inlibglslglsllinux/:home/ -//.225/.functionoptimizer_d.aglcpp..:muhznit. (/./ //`pp.opp.c/linux64_gccundefinedMuhznitlinux64_gccglcpp_preprocess):./ //':227.binreferencegitreposbin: :// //
In .libglsltomudlibglsl/ undefined.- --homefunction /optimizer_d.a`sampleoptimizer_d.a/ referencemud(/glcpp_lex_set_source_string(muhznit` /pp.obuild'pp.o/glcpp_preprocessto3rdparty)/
)Muhznit' /:projects/:/:`bgfx /home gitrepos
glcpp_parser_parse/Ingmake/In//'3rdparty -muhznit mudhome
/functionlinux/function-/.glsl /Muhznit samplemuhznit.-`./`///optimizerglcpp_preprocess.gitreposglcpp_preprocessbuildMuhznit./'//'//.src:.mud:projectsgitrepos//
.-
//linux64_gccglsl//sample/gmakemud//home./home--binglcpp/.build/linuxsample//muhznit//muhznit//libglslpp.c/mudprojects/.build-:Muhznit//Muhznit./optimizer_d.a225/3rdpartygmake//projects(:gitrepos/-gitrepos./glcpp /bgfxlinux/.gmake-undefinedmud//mud/-parse.o -3rdparty.-.linux)referencesample/.sample./: /glsl///. tobuild-.buildmud.In /optimizer./// `projects//projects3rdparty.function/glcpp_lex_set_source_stringsrc.//. gmake'/.gmakebgfx/`-
glsl/-/.yyparselinux//mudlinux3rdparty.'/homeglcpp////:.//3rdparty.glslmud
.muhznitpp.c/.-////:bgfx/optimizer3rdpartyhome.Muhznit225/.///./:3rdparty.srcbgfxmuhznit/gitrepos /////./undefinedglsl.glsl3rdpartyMuhznit.mud -.////-referenceoptimizer/glcppglslgitreposmudsample /mud/-///tosrc/pp.coptimizermud3rdpartybuild /3rdparty:/-//`glsl/225srcsamplebgfxprojects/glcpp_lex_set_source_stringbgfx:////glcpp'/ glslbuild3rdpartygmake/
3rdpartyundefined///-pp.c// glcppprojectsglsllinux:homeglslreference//-/227/- pp.cgmakeoptimizer.:muhznitoptimizerto:-/. // 225linuxsrc/undefinedMuhznitsrc`://. //glcpp_lex_set_source_string y.tab.cglsl.referencegitreposglsl'undefined:// //
 1705glcpp.tomudglcpp/reference:/. -/home  pp.c/`samplepp.c/toundefined:mudglcpp_parser_parse/:muhznit  225/'build225/`reference:3rdparty
/:Muhznitglcpp_lex_set_source_string  /.projects /'toundefinedbgfx./undefinedgitrepos
  //gmake //`reference3rdparty.-referencemudhomeyylex /.linux -/'toglsl//tosamplemuhznit
 -linux64_gcc. //.`optimizer/.`buildMuhznit.glcpp_lex_set_source_string/bin/glcpp_lex_set_source_string///'src/.'projectsgitrepos.
/libglsl.
//./glsl-//gmakemud/home/optimizer_d.a.home--linux64_gcc/glcpp(./linuxsample/muhznit/glcpp/muhznit//bin/pp.c-mud/.build/Muhznit:parse.o/Muhznit./libglsl/227)3rdparty//projects-gitrepos::/gitrepos./optimizer_d.a/  bgfx/.gmake(mudundefinedIn/mud/-glcpp-  3rdparty-.linux-samplereferencefunction/sample./parse.o/  glsl//.)buildto`-buildmud.:/ yyparseoptimizer/// projects`'/projects3rdparty.In/glcpp_parser_parse:src//. gmake'
/gmakebgfx/function-
/glsl-/. linux.home/linux3rdparty.`/./glcpp///glcpp_parser_create./muhznit/.glslmud'../pp.c.-/:/.Muhznit:/optimizer3rdparty
.//227.///.linux64_gccgitrepos:.srcbgfxhome/// ////.binmudundefined.glsl3rdpartymuhznit./- .////libglslsamplereference/glcppglslMuhznitmud-/ mud/-//optimizer_d.abuildto/pp.coptimizergitrepos3rdparty(/ 3rdparty:///glcppprojects`/227srcmudbgfx-/glcpp_parser_parsebgfx:/-/parse.ogmake'/ glslsample3rdparty)-
3rdpartyundefined///:linux./ glcppbuildglsl /.glslreference//-Iny.tab.c/- pp.cprojectsoptimizer :.optimizerto://function1705./ 227gmakesrc :/src`:-/` linux64_gcc/glcpp_parser_parse linuxglslyyparseundefined/glsl'undefined//' bin/
 .glcpp:reference/glcpp.reference./
 libglsl/. /pp.c/to-pp.c/to.:home optimizer_d.a:. .227/`(227.`/:muhznityylexglcpp:/glcpp_parser_parse. /'- linux64_gcc'.undefinedMuhznit
parse.oundefined/
/ /.) bin.mudreferencegitrepos.:reference/./ //  libglsl/3rdpartytomud.Into-./ -.  optimizer_d.a.bgfx`sample/function`(//glcpp_parser_parse/linux64_gcc glcpp_parser_parseglcpplinux64_gcc3rdparty'build/`'-//
/binyyparse
parse.obinglsl.projects/'.)/-./libglsl:.:libglsloptimizer/gmake-
/ -/.-optimizer_d.a/.Inoptimizer_d.asrc.linux(home. (///glcpp//functionglcppglsllinux64_gccy.tab.c-muhznitlinux64_gcc -//:parse.o//`parse.oglcppbin1705)Muhznitbinyyparse)//:://':glcpplibglsl  gitreposlibglsl: --undefinedIn/-
Inparse.yoptimizer_d.a  mudoptimizer_d.a/ :(referencefunction-(homefunction1345glcpp  sampleglcpp/ :-to`/-muhznit` parse.o glcpp_parser_createbuildparse.o/yyparseundefined)`'/)Muhznit' :yylex:projects:/:reference '
/ gitrepos
 In
/gmakeIn//to .home- mudhome function./linuxfunction-/` /muhznit/ samplemuhznitglcpp_lex_init_extra`./y.tab.c`//'yyparse.Muhznit:yyparsebuildMuhznit
'//1705'//.:linux64_gccgitrepos::projectsgitrepos.
//
////binmudundefined/gmakemud.home/- home--./libglslsamplereference/linuxsample/muhznit-/ muhznit//linux64_gcc/optimizer_d.abuildto/y.tab.cbuild/Muhznit(/ Muhznit:/bin/glcppprojects`/1705projects/gitrepos-/yylexgitrepos:/libglsl/parse.ogmake'/ gmake-mud)-
mudundefined-optimizer_d.a-:linux.- linux(sample /.samplereference/glcpp/In.// y.tab.c-build ..buildto:parse.o/function/./ 1705)projects ./projects`::/`.linux64_gcc/yylex  gmakeglcpp_parser_create//gmake'undefinedIn-'.bin-
  linux:./linux.referencefunction/
/libglsl/.  y.tab.c/mud-y.tab.c/to`:home/optimizer_d.a:. glcpp_parser_destroy1705/3rdparty(1705.`':muhznit/glcpp:/yylex: /bgfx- linux64_gcc'
undefined/Muhznitparse.oundefined/
/ 3rdparty/) bin.homereference/gitrepos:reference/./ glsl/  libglsl/muhznitto-mudInto-./ optimizer-  optimizer_d.a.Muhznit`/samplefunction`(//yylexsrc/ yylexglcpplinux64_gccgitrepos'/build`'-//
glsl/glcpp_parser_create
parse.obinmud./projects'.)/-.glcpp/:.:libglslsample//gmake
/ -/.glcpp-/.Inoptimizer_d.abuild.-linuxhome. (//parse.y///functionglcppprojectslinux64_gcc:.muhznitlinux64_gcc -//1345.//`parse.ogmakebin:/Muhznitbinglcpp_parser_create)-/ .//':linuxlibglslundefined.gitreposlibglsl: /- //-
In.optimizer_d.areference.mudoptimizer_d.a/ .( .-(homefunction/glcppto/sampleglcpp/ .- mud/-muhznit`.parse.o`/buildparse.o/glcpp_parser_create/)glcpp_lex_init_extra3rdparty/)Muhznit'.:'/projects:/:.
bgfx/ gitrepos
/In./gmakeIn//mud .3rdparty- mudhome/function//linuxfunction-/3rdparty .glsl/ samplemuhznit/`.-.`//bgfxglcpp_parser_create/optimizer.glcpp_parser_createbuildMuhznit/'linux64_gcc//'//3rdparty:/src.:projectsgitrepos/
bin/.
//glsl//glsl//gmakemud-homelibglsl/.home--optimizer/-glcpp./linuxsample/muhznitoptimizer_d.a//muhznit//src/(glcppmud/.build/Muhznitglcpp-/Muhznit./glsl/-parse.y3rdparty//projects/gitreposparse.o:/gitrepos./glcpp/)1345bgfx/.gmake/mud::/mud/-glcpp-  3rdparty-.linux-sampleInundefined/sample./parse.y/  glsl//.:buildfunctionreference-buildmud.1386/  optimizer///:projects`to/projects3rdparty. /glcpp_parser_destroy src//.undefinedgmake'`/gmakebgfx/ -:glcpp_lex_init_extraglsl-/.referencelinux
'/linux3rdparty. //
glcpp///to.home./.glslmud ./.glcpp.-/`/muhznit/-/optimizer3rdpartyglcpp_lex_destroy./.parse.y.//'.Muhznit.:.srcbgfx
///1345///..gitreposlinux64_gcc:.glsl3rdparty..// .////mudbinundefined/glcppglsl.mud-/ mud/-./samplelibglslreference/glcppoptimizer/3rdparty/- 3rdparty-/linux64_gcc/buildoptimizer_d.ato/parse.ysrc/bgfx/( bgfx:/bin/projectsglcpp`/1345glsl/3rdparty/-glcpp_lex_init_extra3rdparty:/libglsl/gmakeparse.o'/ glcpp-glsl-)
glslundefined/-optimizer_d.alinux:.- glcppoptimizer(/ .optimizerreference-/glcpp.In// parse.ysrc-. .srcto:/parse.o/function./ 1345glsl). /glsl`:/:.`linux64_gcc/glcpp_lex_init_extra glcpp /glcpp_parser_destroy/glcpp'undefined/In.'bin/
 glcpp .:/glcpp.reference-function/
libglsl-. parse.y mud/-parse.y/to:`/homeoptimizer_d.a:. 1345glcpp_parser_lex3rdparty/(1345.`:'/muhznitglcpp:/glcpp_lex_init_extra :bgfx/- linux64_gcc'undefined
/Muhznitparse.oundefined/
 /3rdparty/) bin.referencehome/gitrepos:reference/. /glsl/  libglsl/tomuhznit-mudInto-. /optimizer-  optimizer_d.a.`Muhznit/samplefunction`(/glcpp_lex_init_extra/src/ glcpp_lex_init_extraglcpplinux64_gcc'gitrepos/build`'-/
/glsl/glcpp_parser_destroy
parse.obin.mud/projects'.)/.-glcpp/:.:libglsl/sample/gmake
/ -./glcpp-/.Inoptimizer_d.a.build-linuxhome. (//parse.y///functionglcpplinux64_gccprojects:.muhznit linux64_gcc-//1386./`/parse.obingmake:/Muhznitglcpp_parser_destroybin)/- ./'/:libglsllinuxundefined.gitrepos:libglsl -/ //
-Inoptimizer_d.a.reference.mud/optimizer_d.a (. .-home(functionglcpp/to/sample/glcpp -. mud/muhznit-`parse.o.`/build/parse.oglcpp_parser_destroy)/glcpp_lex_destroy3rdparty/Muhznit)':.'/projects/:: .
bgfx/gitrepos
In/./gmake/In/ mud.3rdparty-mud homefunction///linux-function/ 3rdparty.glsl/sample muhznit`/.-./`/glcpp_parser_destroybgfx/optimizer.buildglcpp_parser_destroyMuhznit'/linux64_gcc///'/:3rdparty/src.projects:gitrepos
/bin/./
//glsl/glsl/gmake/mudhome-libglsl/.-home-/optimizer-glcpp.linux/samplemuhznit//optimizer_d.a//muhznit//srcglcpp(mud./buildMuhznit/-glcpp/.Muhznit//glslparse.y-3rdparty//projectsgitrepos/:parse.o/.gitrepos//glcpp1386)bgfx./gmakemud/:://mud--glcpp  3rdparty.-linuxsample-undefinedIn/.sample//parse.y  glsl//.build:referencefunction-mudbuild./2197  optimizer///projects:to`/3rdpartyprojects./  glcpp_parser_lexsrc//.gmakeundefined`'/bgfxgmake/- glcpp_lex_destroy:glsl/-.linuxreference'
/3rdpartylinux./
/glcpp///.to.home/glsl.mud. ./glcpp-.//`/muhznit-optimizer/3rdparty.glcpp_lex./parse.y/./.'.Muhznit:src.bgfx/
//1386///.linux64_gccgitrepos:glsl.3rdparty.// /.//binmudundefinedglcpp/glslmud/- /mud-/libglslsamplereferenceglcpp/optimizer3rdparty-/ -3rdparty//optimizer_d.abuildtoparse.y/srcbgfx(/ :bgfx//glcppprojects`1386/glsl3rdparty-/glcpp_lex_destroy:3rdparty//parse.ogmake' /glcppglsl)-
undefinedglsl/-:linux. -glcppoptimizer /.referenceoptimizer-/In./ /parse.ysrc ..tosrc:/function/. /1386glsl ./`glsl:/`.linux64_gccglcpp_lex_destroy/ glcppglcpp_parser_lex//'glcppundefined/'.bin
/ glcpp:./.glcppreference-
/libglsl.- parse.y/mud-/parse.yto:home/.optimizer_d.a: 13863rdparty./(1386`://muhznitglcpp:glcpp_lex_destroy bgfxlinux64_gcc/- 'undefined//Muhznitparse.oundefined
 3rdpartybin/) .reference//gitrepos:reference. glsllibglsl/  /to--mudInto. optimizeroptimizer_d.a-  .`/(samplefunction`/glcpp_lex_destroysrcglcpp/ glcpp_lex_destroylinux64_gcc'/-build`'/
glslparse.o/glcpp_parser_lex
bin./)projects'./.glcpp:/:.libglsl// gmake
/-.glcppIn-/.optimizer_d.a.- linuxhome.(/parse.yfunction///glcpplinux64_gcc: .muhznitlinux64_gcc-/2197`.//parse.obin:glcpp_parser_lex/Muhznitbin)/ './/:libglslundefined:.gitreposlibglsl -
//-Inoptimizer_d.areference/.mudoptimizer_d.a ( home.-(functionglcppto//sampleglcpp - muhznitmud/-`parse.o`//buildparse.oglcpp_parser_lex)glcpp_lexMuhznit3rdparty/)':'//projects::
gitreposbgfx/
In//gmakeIn/ mud3rdparty- homefunction-/linuxfunction/ sampleglsl/ muhznit`/-.`/glcpp_parser_lexbuildoptimizer.glcpp_parser_lexMuhznit'///'/:projectssrc.:gitrepos
//.
//gmakeglsl//mudhome-/.home-/linuxglcpp./samplemuhznit///muhznit//.glcppmud/buildMuhznit.-/Muhznit///parse.y3rdparty/projectsgitrepos.:/gitrepos//.2197bgfx/gmakemud/:/mud--. 3rdparty-linuxsample.undefined/sample/// glsl/.buildmudreference-build.// optimizer//projects3rdpartyto/projects.// src/.gmakebgfx`/gmake/-/glcpp_lexglsl-.linux3rdparty'/linux.//
glcpp//.glsl/.mud.-glcpp.//optimizer-/3rdparty./parse.y./.src:.bgfx//2197//.glsl:.3rdparty./ .//glcppundefined/glslmud/ mud-/glcppreference/optimizer3rdparty- 3rdparty//parse.yto/srcbgfx: bgfx//2197`/glsl3rdparty:glcpp_lex3rdparty// '/glcppglslundefined
glsl/- -glcppoptimizerreferenceoptimizer-/ /parse.ysrctosrc:/ /2197glsl`glsl:/glcpp_lex/ glcpp'glcppundefined/
/ glcppglcppreference-- parse.yparse.yto:: 21972197`::collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
glcpp_lexcollect2: error: ld returned 1 exit status
  'undefinedundefined
  referencereference  toto collect2: error: ld returned 1 exit status
 ``glcpp_lexglcpp_lex''

collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
01_shapes.make:198: recipe for target '../../linux64_gcc/bin/01_shapes_d' failed
make[1]: *** [../../linux64_gcc/bin/01_shapes_d] Error 1
00_tutorial.make:207: recipe for target '../../linux64_gcc/bin/00_tutorial_d' failed
make[1]: *** [../../linux64_gcc/bin/00_tutorial_d] Error 1
Makefile:96: recipe for target '01_shapes' failed
make: *** [01_shapes] Error 2
make: *** Waiting for unfinished jobs....
Makefile:88: recipe for target '00_tutorial' failed
make: *** [00_tutorial] Error 2
04_lights.make:208: recipe for target '../../linux64_gcc/bin/04_lights_d' failed
make[1]: *** [../../linux64_gcc/bin/04_lights_d] Error 1
Makefile:108: recipe for target '04_lights' failed
make: *** [04_lights] Error 2
02_camera.make:203: recipe for target '../../linux64_gcc/bin/02_camera_d' failed
make[1]: *** [../../linux64_gcc/bin/02_camera_d] Error 1
Makefile:104: recipe for target '02_camera' failed
make: *** [02_camera] Error 2
06_particles.make:198: recipe for target '../../linux64_gcc/bin/06_particles_d' failed
make[1]: *** [../../linux64_gcc/bin/06_particles_d] Error 1
Makefile:116: recipe for target '06_particles' failed
make: *** [06_particles] Error 2
00_cube.make:198: recipe for target '../../linux64_gcc/bin/00_cube_d' failed
make[1]: *** [../../linux64_gcc/bin/00_cube_d] Error 1
Makefile:92: recipe for target '00_cube' failed
make: *** [00_cube] Error 2
04_sponza.make:208: recipe for target '../../linux64_gcc/bin/04_sponza_d' failed
make[1]: *** [../../linux64_gcc/bin/04_sponza_d] Error 1
Makefile:112: recipe for target '04_sponza' failed
make: *** [04_sponza] Error 2
03_materials.make:198: recipe for target '../../linux64_gcc/bin/03_materials_d' failed
make[1]: *** [../../linux64_gcc/bin/03_materials_d] Error 1
Makefile:100: recipe for target '03_materials' failed
make: *** [03_materials] Error 2

**Comment by hugoam** [comment]
The log output is all messed up because of the `-j8` : in the future when sending errors you might want to run it without `-j8` so we get a readable non mixed-up output

I think the problem is most likely that some files in glsloptimizer where overwritten by the build. This happen on linux and I have no idea why.
Go in `3rdparty/bgfx` then `git checkout .` (this should fix a couple of files)
Then rebuild.

**Comment by CarvellScott** [comment]
Bad news: `git checkout .` in 3rdparty/bgfx did nothing.
Good news: It successfully compiled with `make config=debug64`!
Bad news: The compile took 3 hours or so, and they're all linux executables, so I can't see how they'd run on my Windows machine. RIP. 😭 
Good news: I got all the build output in a hastebin: https://hastebin.com/opivayofud.sql

**Comment by hugoam** [comment]
Well yep, you just built a linux binary, not a windows executable !
If you want to build a windows executable you need to build with Visual Studio.
The only way you can run a graphical app with WSL is with a X server app like MobaXterm, but the framerate will probably make it utterly useless.
