### ISSUE TITLE
On OSX : mud/bin/genie: cannot execute binary file

### ISSUE THREAD

**Issue by QuantScientist** [hugoam/mud#6]
Hi,
Followed your instructions but getting this on OSX:
nsa-000:mud-sample freebsd$ mud/bin/genie 
-bash: mud/bin/genie: cannot execute binary file

**Comment by QuantScientist** [comment]
Found the correct one however now I am getting:
nsa-000:mud-sample freebsd$ mud/bin/genie --gcc=linux-gcc gmake
cannot open /Users/freebsd/repo/_dev/mud-sample/mud/3rdparty/bx/scripts/bx.lua: No such file or directory
stack traceback:
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:96: in function 'dofile'
	.../repo/_dev/mud-sample/mud/scripts/3rdparty/bgfx/bgfx.lua:6: in main chunk
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:96: in function 'dofile'
	/Users/freebsd/repo/_dev/mud-sample/mud/scripts/mud.lua:6: in main chunk
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:96: in function 'dofile'
	/Users/freebsd/repo/_dev/mud-sample/scripts/genie.lua:22: in main chunk
	[C]: in upvalue 'builtin_dofile'
	[string "premake = { }..."]:96: in function 'dofile'
	[string "_WORKING_DIR        = os.getcwd()..."]:45: in function '_premake_main'

**Comment by hugoam** [comment]
Hi !
- I didn't include OSX genie binaries because I don't have an OSX computer.
The genie binary you are running was compiled with linux so I'm not sure it is supposed to work on OSX.
You can build genie from source by going in `3rdparty/GENie/build/gmake.darwin`, and building that with make.
Put the resulting binary anywhere you like (for example `mud\bin\darwin` would be a good place) and run the commands with that one instead of the one in `mud\bin`
- The second error simply seems to be caused by the fact you didn't get all the submodules recursively, sor the `mud/3rdparty/bx` folder is probably empty. If you didn't clone with `--recursive` or if there was an issue go in the mud folder and run `git submodule update --init`

**Comment by QuantScientist** [comment]
Thanks!
Resolving deltas: 100% (527/527), done.
Cloning into '/Users/freebsd/repo/_dev/mud-sample/mud/3rdparty/vorbis'...
remote: Counting objects: 16260, done.        
remote: Compressing objects: 100% (14/14), done.        
remote: Total 16260 (delta 8), reused 12 (delta 6), pack-reused 16240        
Receiving objects: 100% (16260/16260), 28.38 MiB | 2.70 MiB/s, done.
Resolving deltas: 100% (12812/12812), done.
Submodule path 'mud/3rdparty/FastNoise': checked out 'faba4443efcd85ad55bf5dd85c8ee458d427d6aa'
error: Server does not allow request for unadvertised object 82cf20e4fb0472b69aac01afe3e79c7a207d631a
Fetched in submodule path 'mud/3rdparty/GENie', but it did not contain 82cf20e4fb0472b69aac01afe3e79c7a207d631a. Direct fetching of that commit failed.
Failed to recurse into submodule path 'mud'

Seems like a problem with one of the submoduls.

**Comment by QuantScientist** [comment]
Thanks for the effort.
I am working on win 10, vc 17, should I still use:
```
genie.exe --gcc=linux-gcc gmake ?
```
I have no executables under bin:
![image](https://user-images.githubusercontent.com/18743986/41733580-ee347738-758c-11e8-89fe-6bf65eec9546.png)

**Comment by QuantScientist** [comment]
Ok found that for Win 10 its:
```
genie.exe vs2017
```
Lets see how it works

**Comment by QuantScientist** [comment]
![image](https://user-images.githubusercontent.com/18743986/41734630-38c29fde-7590-11e8-9ba3-e6d7c894ad87.png)

exe created by execution crashes; should I run from a nother dir?

**Comment by hugoam** [comment]
It's been a while and mud has changed a lot. OSX build is fixed, but has some issues running with the Metal backend (see https://github.com/hugoam/mud/issues/7). Please reopen an issue if you can produce a stacktrace that crashes on windows with the latest version.
